color_list=set(['white','black','red'])
color_list1=set(["red",'green'])
print("orginal set elements")
print(color_list)
print(color_list1)
print("\n difference of color_list and color_list1")
print(color_list-color_list1)
print("\n difference of color_list1 and color_list")
print(color_list1-color_list)
